### PR TITLE
Remove unnecessary feature spec.

### PR DESCRIPTION
**Pull request by eschlange**
* Removing redundant feed item check feature test.

[Finished #92039626]

### CODE REVIEW

**Comment by eschlange** [comment]
@ericcf Chris B wants your confirmation that this you are on board with the removal of this feature spec.

**Comment by ericcf** [comment]
Would you mind linking to the other specs that cover the feed for audio slides?

**Comment by eschlange** [comment]
@ericcf How does the removed spec cover the feed for audio slides? That feed item is seeded via fixtures. Are you asking me where are other tests that confirm that feed items appear in the feed?

**Comment by ericcf** [comment]
Based on the title "Participant has accessed audio slide", I assumed it was testing whether audio slide accesses show up in the feed. As long as there's at least some code that tests whether a shared audio slide access works, this removal seems fine.

**Comment by eschlange** [comment]
@ericcf I understand, I'll check through the SocialNetworking project to determine if there is a test for audio slide feed item creation. If it doesn't exist, I'll write one.

**Pull request closed without merging**
