### PR TITLE
Add repeatable incentive

### PR DESCRIPTION
**Pull request by cbrenner04**
* Add incentive, behavior, participant incentive, and participant behavior
* Add a completed behavior so it will list it as once complete

### CODE REVIEW

**Comment by cbrenner04** [comment]
nobody touch this yet ... @eschlange and I trying to troubleshoot an issue I am having with it

**Comment by cbrenner04** [comment]
ok this should be good now

**Comment by michaelwehrley** [comment]
looks good to me! :pizza:

**Comment by cbrenner04** [comment]
@eschlange this should be good now. Thanks!

**Pull request merged**
