### PR TITLE
Add profile for participant1

### PR DESCRIPTION
**Pull request by cbrenner04**
* Not having a profile introduced odd behavior with activity feed

### CODE REVIEW

**Comment by cbrenner04** [comment]
@michaelwehrley so for some reason not having a profile for participant1 meant no one in the group could see the activity feed until the participant hit the profile page to activated their profile. Very weird. Thought you'd like to know since we were talking about this earlier

**Comment by michaelwehrley** [comment]
Yeah, I spent a few hours trying to debug an issue related to this this morning.  Arg!  Thanks for the heads up.

**Comment by michaelwehrley** [comment]
We will need to revisit this.

**Comment by michaelwehrley** [comment]
:+1: :pizza:

**Pull request merged**
