### PR TITLE
Update profile question styles according to mockup

### PR DESCRIPTION
**Pull request by Wrenderer**
* Replace listgroups with panels (`.panel-success`), this was mostly done
 * Wrap existing panels in main "Profile" panel
 * Place edit button and answer text in `.media` layers to ease alignment and remove `.edit-link` custom class

[Finished: #97428316]

### CODE REVIEW

**Comment by eschlange** [comment]
That is some good looking bootstrap/angular. :+1:

**Comment by eschlange** [comment]
Looks like you'll need to merge this in manually.~

**Comment by Wrenderer** [comment]
Thanks! On it.

**Comment by michaelwehrley** [comment]
@Wrenderer Great!  After updating those gems I was trying to deploy, but I kept getting a failing spec. After you rebase, let me know if you keep getting a failing spec in "/spec/features/social_networking/home_tool_spec.rb"  Thanks!

**Comment by Wrenderer** [comment]
@michaelwehrley Rebased, had to change a spec because the new panel wrapping was causing it to find ambiguous matches, but after that change I'm not getting any failing specs locally or otherwise.

**Comment by eschlange** [comment]
:+1:

**Pull request merged**
