### PR TITLE
Add Dynamic h3 Heading

### PR DESCRIPTION
**Pull request by michaelwehrley**
Add Dynamic h3 Heading

* Heading that notifies user to complete profile is dynamic.
* Heading hides after the user starts completing one profile question.
* Additional code referencing `onReady` removed - function doesn't exist.
* `onReady` function was breaking throwing js errors.

[Finished: #97428814]

### CODE REVIEW

**Comment by cbrenner04** [comment]
@michaelwehrley is this only in sunnyside or are you going to have to do similar work in think_feel_do_so?

**Comment by michaelwehrley** [comment]
@cbrenner04 I already made the change on think_feel_do_so. :smile:

**Comment by cbrenner04** [comment]
@michaelwehrley great! :+1:

**Comment by michaelwehrley** [comment]
yep - https://www.youtube.com/watch?v=-rHplEFYKsk

**Comment by eschlange** [comment]
:pizza:  :bee:

**Pull request merged**
